#!/bin/bash

# Define the source and destination for the scp command
SOURCE="../build/VGG16"
DESTINATION="root@localhost:/root/VGG16"

# Define the port
PORT=2222
SSH_KEY="/home/samjons/thesis/dqib_riscv64-virt/ssh_user_ed25519_key" # Update this path to your SSH key location

# Execute the scp command
scp -P $PORT -i $SSH_KEY $SOURCE $DESTINATION

# Check if scp was successful
if [ $? -eq 0 ]; then
    echo "VGG16 has been successfully copied to the destination."
else
    echo "Failed to copy VGG16 to the destination."
fi
